Neos:
  Flow:
    mvc:
      routes:
        'NeosRulez.Neos.SSHTerminal': true
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'NeosRulez.Neos.SSHTerminal:Commands':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'NeosRulez\Neos\SSHTerminal\Controller\.*'
  Neos:
    Ui:
      resources:
        stylesheets:
          NeosRulez.Neos.SSHTerminal:
            resource: '${"resource://NeosRulez.Neos.SSHTerminal/Public/Plugin.css"}'
        javascript:
          NeosRulez.Neos.SSHTerminal:
            resource: '${"resource://NeosRulez.Neos.SSHTerminal/Public/Plugin.js"}'
      frontendConfiguration:
        'NeosRulez.Neos.SSHTerminal:Terminal:Settings': '${Configuration.setting(''NeosRulez.Neos.SSHTerminal'')}'
        'NeosRulez.Neos.SSHTerminal:Terminal:Role': '${Security.hasRole("Neos.Neos:Administrator") ? true : false}'
NeosRulez:
  Neos:
    SSHTerminal:
      safeMode: true
      fakeUser: 'neos'
      splashScreen: true
